version: '3.8'

services:
  db:
    image: postgres:12.1-alpine
    container_name: pleroma_db
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
    networks:
      - nginx
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  web:
    image: pleroma
    container_name: pleroma_web
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider --proxy=off localhost:4000 || exit 1",
        ]
    networks:
      - nginx
    restart: always
    expose:
      - 4000
    build:
      context: .
      args:
        - "UID=${UID}"
        - "GID=${GID}"
        - "PLEROMA_VER=${PLEROMA_VER}"
    volumes:
      - ./uploads:/var/lib/pleroma/uploads
      - ./static:/var/lib/pleroma/static
      - ./prod.secret.exs:/usr/local/pleroma/config/prod.secret.exs:ro
    environment:
      DOMAIN: ${DOMAIN}
      INSTANCE_NAME: ${INSTANCE_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      NOTIFY_EMAIL: ${NOTIFY_EMAIL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db

networks:
  nginx:
    external: true
    name: nginx